### ISSUE TITLE
Can you provide some results from the trained model?

### ISSUE THREAD

**Issue by luowy1001** [tomguluson92/StyleGAN_PyTorch1.0.1#1]
First, thanks for your great work！
And can you provide some results from the trained model?

**Comment by tomguluson92** [comment]
Thank you, our model was not meant to release now, the project here was meant to transport the code seamlessly from original tensorflow to pytorch. If you need a pretrained model, you can train it on your own dataset. I see no obstacle to customize your own dataset into this project (Unless you gonna use it for multi-class image generation task). You can feel free to contact me via qq: 314913739.

**Comment by luowy1001** [comment]
Thanks for your great help！ I think it is very likely that there will be some problems one day and I need to trouble you. Now, I am trying to train the model on some datasets using the workstation.

**Comment by tomguluson92** [comment]
Close
