### ISSUE TITLE
what are the information stored on the pkl file?

### ISSUE THREAD

**Issue by Naveennavik** [tomguluson92/StyleGAN_PyTorch1.0.1#14]
karras2019stylegan-ffhq-1024x1024.pkl 
whether the above file contains training dat info or the dataset info?
or the both on the ffhq pkl file
reply me once u go through this!

**Comment by tomguluson92** [comment]
Hi, I do not dive too much in karras original repo. So the detail about xxx.pkl for me is still a black box.
