### ISSUE TITLE
Question about the styleGAN performance  in pytorch

### ISSUE THREAD

**Issue by EricKani** [tomguluson92/StyleGAN_PyTorch1.0.1#4]
Hi~ 

Very thanksful for your pytorch code sharing. I am very interested in the performance of the this styleGAN in pytorch. Have you test it in some metric, like FID, or check the generated results in the middle phase of training?

thanks,

EK

**Comment by tomguluson92** [comment]
Hi Eric, 
     I haven't tried to do so because i am not work for this recently, i only test on few datasets and since the lack of graph card, i only do some simplest demo. here is the 1024 x 1024 intermediate output during my training process.


![26_shrink](https://user-images.githubusercontent.com/19585240/63204746-aa547080-c0cd-11e9-894a-a605bc8ddfe0.png)

**Comment by EricKani** [comment]
Hi~ @tomguluson92 Thanks for your reply~ I am interested in this work. Maybe I can finish it.

**Comment by tomguluson92** [comment]
> Hi~ @tomguluson92 Thanks for your reply~ I am interested in this work. Maybe I can finish it.

Sounds great! Hope you can finish it and pull request to improve this project~

**Comment by XiaotianM** [comment]
> Hi Eric,
> I haven't tried to do so because i am not work for this recently, i only test on few datasets and since the lack of graph card, i only do some simplest demo. here is the 1024 x 1024 intermediate output during my training process.
> 
> ![26_shrink](https://user-images.githubusercontent.com/19585240/63204746-aa547080-c0cd-11e9-894a-a605bc8ddfe0.png)

how long have you trained for these results?
