### ISSUE TITLE
Question about Adaptive Instance Normalization 

### ISSUE THREAD

**Issue by houxianxu** [tomguluson92/StyleGAN_PyTorch1.0.1#8]
Thanks for sharing the code.

As shown in the [line](https://github.com/tomguluson92/StyleGAN_PyTorch/blob/a44b0e11aaf54fe18bed91b4f5261196fafb4c9f/networks_stylegan.py#L51) below. Why do you add x when performing the instance normalization? 

`x = x * (style[:, 0] + 1.) + style[:, 1]`

All the best,
Xianxu

**Comment by tomguluson92** [comment]
Hi hou, 
         The line `x = x * (style[:, 0] + 1.) + style[:, 1]` is used in sty;le applying indeed, it's not about instance norm, maybe you can read it carefully~

**Comment by houxianxu** [comment]
@tomguluson92 
Thanks for your reply. My question may be a little confusion. What I mean is indeed the styling part of adaptive instance normalization.

The adaptive instance normalization is as follows:
![image](https://user-images.githubusercontent.com/3723839/64524807-f2179200-d331-11e9-9abb-0f5837bddb19.png)

If I am not wrong, the following line 
`x = x * (style[:, 0] + 1.) + style[:, 1]`
should be 
`x = x * style[:, 0] + style[:, 1]`
where x is the normalized version.

**Comment by tomguluson92** [comment]
> @tomguluson92
> Thanks for your reply. My question may be a little confusion. What I mean is indeed the styling part of adaptive instance normalization.
> 
> The adaptive instance normalization is as follows:
> ![image](https://user-images.githubusercontent.com/3723839/64524807-f2179200-d331-11e9-9abb-0f5837bddb19.png)
> 
> If I am not wrong, the following line
> `x = x * (style[:, 0] + 1.) + style[:, 1]`
> should be
> `x = x * style[:, 0] + style[:, 1]`
> where x is the normalized version.

Hi, you are right about the official implementation of IN. However, this version is transported from the referred URL as noted in uncomment part, you can just turn it into an official mode, thanks a lot for your carefulness.
